imageLocation: /usr/share/cikkek
logoImageLocation: /usr/share/logok
dbLocation: /usr/share/db
webImageCacheLocation: /usr/share/cache
renderingLocation: /usr/share/render
webImageURLPrefix: http://www.madalbal.hu/
pagesPerDocumentInQualityMode: 10
itemCategorizerEngineClass: com.himadri.engine.StrictItemCategorizerEngine
spring:
  profiles:
    active: test
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
---
spring:
  profiles: szerszam
instance: szerszam
pageTitle: Szerszám Katalógus
pdfLang: hu
---
spring:
  profiles: bio
instance: bio
pageTitle: Bio Katalógus
pdfLang: hu
---
spring:
  profiles: szerb
instance: szerb
pageTitle: Szerb Katalógus
pdfLang: sr
---
spring:
  profiles: test
instance: test
pageTitle: Teszt Mód
pdfLang: hu
imageLocation: ../cikkek
logoImageLocation: ../logok
dbLocation: ../db
webImageCacheLocation: ../cache
renderingLocation: target/render
